name: Upload Artifact
description: Upload workflow artifacts
inputs:
  name:
    description: Artifact name
    required: true
  path:
    description: Path to artifact
    required: true
runs:
  using: composite
  steps:
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
